services:
  - type: web
    name: payfast-react-php-app
    runtime: docker # Use Docker for our custom environment
    plan: free # Or your preferred plan
    # Docker settings
    dockerfilePath: ./Dockerfile
    # Environment variables are still the same
    envVars:
      - key: PAYFAST_MERCHANT_ID
        fromService:
          type: web
          name: payfast-react-php-app
          envVarKey: PAYFAST_MERCHANT_ID_SECRET
      - key: PAYFAST_MERCHANT_KEY
        fromService:
          type: web
          name: payfast-react-php-app
          envVarKey: PAYFAST_MERCHANT_KEY_SECRET
      - key: PAYFAST_PASSPHRASE
        fromService:
          type: web
          name: payfast-react-php-app
          envVarKey: PAYFAST_PASSPHRASE_SECRET